# netlify.toml
[build]
  functions = "netlify/functions"

# 任意: 覚えやすいショートURL
[[redirects]]
  from = "/oauth/start"
  to = "/.netlify/functions/oauth-start"
  status = 200

[[redirects]]
  from = "/oauth/callback"
  to = "/.netlify/functions/oauth-callback"
  status = 200